2022.26.12 updates
Lockstep-Network/lockstep-sdk-python pull request #31
Opened 2022-07-05 18:48 UTC by AlexRussak

2022-07-09 00:08 UTC, sfwatanabe commented on src/lockstep/models/actionresultmodel.py
> +    messages: list[str] | None = None
I noticed the our setup.cfg indicating support for >= 3.6 but the use of the union pipe operator just got added in 3.10. I can confirm that trying to run this locally causes problems with 3.6. I will follow up with suggestions on the main generator. In the current state we would need to change the min version requirement to 3.10

2022-07-14 17:06 UTC, sfwatanabe requested changes
The `__init__.py` files in both clients and models appear to have gotten removed in this PR. Python needs these to detect available imports during runtime. 

Similar to an `index.ts` you'll see in TypeScript projects although they don't require any code.

2022-07-15 16:22 UTC, AlexRussak commented
> The `__init__.py` files in both clients and models appear to have gotten removed in this PR. Python needs these to detect available imports during runtime.
> 
> Similar to an `index.ts` you'll see in TypeScript projects although they don't require any code.

Fixed!

2022-08-18 17:53 UTC, sfwatanabe commented
In order to support the type hinting union operator `|`, we need to bump the minimum python version to 3.10 in [setup.cfg](https://github.com/Lockstep-Network/lockstep-sdk-python/blob/main/setup.cfg). 

Attempting to install the package currently would only run for 3.10 or higher. We could update the syntax generation to support down to 3.7 in a future PR.

Additionally from a convenience standpoint we should declare the required dependencies - [related issue](https://github.com/Lockstep-Network/lockstep-sdk-python/issues/32)

2022-08-18 20:05 UTC, sfwatanabe approved these changes

2022-08-18 20:23 UTC, merged